### ISSUE TITLE
재료부분 이슈

### ISSUE THREAD

**Issue by dpwls09** [hayoung131/Scraping_recipe#1]
![image](https://user-images.githubusercontent.com/40027664/58247132-e066aa80-7d93-11e9-952a-06cd8c0ec3d7.png)
![image](https://user-images.githubusercontent.com/40027664/58247140-e52b5e80-7d93-11e9-972d-7f2c979e221f.png)
위에서 잘 실행하다가 이렇게 갑자기 에러가 뜸. 그래서 에러가 뜬 레시피 페이지를 찾아가보니 
![image](https://user-images.githubusercontent.com/40027664/58247165-e8bee580-7d93-11e9-818e-af2b97a591d0.png)
이렇게 재료가 '꽈리 고추 두'로 재료명 사이에 공백이 있어서 에러가 남. 
이부분 에러안나게 해결 해야할듯 ㅠ 

c95ede1d584866182c4f7ab138cbb660b77b4a6e

**Comment by hayoung131** [comment]
애초에 웹에서 크롤링해올때, 보니까 계량부분이 따로 있는곳도 있더라!! 재료명 뽑힐때 계량까지 다뽑혀버리는게 문제니깐,,, 계량부분 따로 뽑아서, if문 돌리며, 리스트에서 삭제하는식으로 해보는건 어때?

**Comment by dpwls09** [comment]
이거 해결했다!  재료부분에서 계량부분 비교해서 제거하고나서 공백 제거하고 딕셔터리에 재료들 넣을때 따로 넣었어
